# Generated by Django 5.0.6 on 2024-07-08 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(default='No bio...'),
        ),
        migrations.AddField(
            model_name='user',
            name='pic',
            field=models.ImageField(default='no_picture.jpg', upload_to='users'),
        ),
    ]
