# Generated by Django 5.0.6 on 2024-08-03 01:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cooking_time', models.FloatField(default=0, help_text='in minutes')),
                ('ingredients', models.CharField(max_length=350)),
                ('difficulty', models.CharField(blank=True, default='', max_length=12)),
                ('description', models.TextField(default='No description...', max_length=500)),
                ('pic', models.ImageField(default='no_picture.jpg', upload_to='recipes')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
