# Generated by Django 5.0.6 on 2024-07-02 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cooking_time', models.FloatField(default=0, help_text='in minutes')),
                ('ingredients', models.CharField(max_length=350)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='Easy', max_length=12)),
                ('description', models.TextField()),
            ],
        ),
    ]
